Blog App -validations and model specs.
Fombi-Favour/blog-app-rb pull request #3
Opened 2024-01-11 12:15 UTC by Fombi-Favour

In this activity, we: 
- added validations on User and Post models
- added unit tests for the methods and validations

2024-01-11 21:12 UTC, Lucas-Masaba requested changes
# Hello @Fombi-Favour  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- Validations working :+1: 

## Required Changes ♻️
_Check the comments under the review._
- [ ] 8 out of 10 of your written tests are failing as seen below. Please make sure all your written tests are passing.
![image](https://github.com/Fombi-Favour/blog-app-rb/assets/45460192/26982b0f-5f79-4557-a6d8-19ab0db60516)


## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-11 21:12 UTC, Lucas-Masaba commented on spec/models/user_spec.rb
> +require 'rails_helper'
- [ ] Custom methods in the models should have corresponding unit tests. Please test the `recent_post` method in your User model

2024-01-11 21:12 UTC, Lucas-Masaba commented on spec/models/post_spec.rb
> +require 'rails_helper'
- [ ] Custom methods in the models should have corresponding unit tests. Please test the `recent_comments` method in your Post model

2024-01-11 21:12 UTC, Lucas-Masaba commented on spec/models/like_spec.rb
> +require 'rails_helper'
- [ ] Custom methods in the models should have corresponding unit tests. Please test the `like_counter_update` method in your Like model

2024-01-11 21:12 UTC, Lucas-Masaba commented on spec/models/comment_spec.rb
> +require 'rails_helper'
- [ ] Custom methods in the models should have corresponding unit tests. Please test the `comment_counter_update` method in your Comment model

2024-01-13 00:12 UTC, Efiamotu-1 requested changes
Hi @Fombi-Favour , 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-13 00:12 UTC, Efiamotu-1 commented on spec/models/post_spec.rb
- [ ] Good job fixing the tests that were not working as requested by the previous reviewer however you are yet to add unit tests for the methods created in the post model as requested by the previous reviewer in this [review link](https://github.com/Fombi-Favour/blog-app-rb/pull/3#discussion_r1449395161), please kindly add them and resubmit for approval :+1: :sparkles:

2024-01-13 00:12 UTC, Efiamotu-1 commented on spec/models/user_spec.rb
- [ ] Good job fixing the tests that were not working as requested by the previous reviewer however you are yet to add unit tests for the methods created in the user model as requested by the previous reviewer in this [review link](https://github.com/Fombi-Favour/blog-app-rb/pull/3#discussion_r1449394631), please kindly add them and resubmit for approval :+1: :sparkles:

2024-01-13 00:12 UTC, Efiamotu-1 commented on spec/models/like_spec.rb
- [ ] Good job fixing the tests that were not working as requested by the previous reviewer however you are yet to add unit tests for the methods created in the like model as requested by the previous reviewer in this [review link](https://github.com/Fombi-Favour/blog-app-rb/pull/3#discussion_r1449395928), please kindly add them and resubmit for approval :+1: :sparkles:

2024-01-13 00:12 UTC, Efiamotu-1 commented on spec/models/comment_spec.rb
- [ ] Good job fixing the tests that were not working as requested by the previous reviewer however you are yet to add unit tests for the methods created in the comment model as requested by the previous reviewer in this [review link](https://github.com/Fombi-Favour/blog-app-rb/pull/3#discussion_r1449397541), please kindly add them and resubmit for approval :+1: :sparkles:

2024-01-13 02:00 UTC, zieeco requested changes
Hi @Fombi-Favour,

<img height="80" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>



Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Nice effort making the requested changes. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-13 02:00 UTC, zieeco commented on spec/models/post_spec.rb
> +      initial = User.find(1).post_counter
![image](https://github.com/Fombi-Favour/blog-app-rb/assets/59397159/9bac0d6a-1db6-4fc4-bb1b-c31593f88283)
---
- Your test is failing, please, see the image for the detailed error to fix it.

2024-01-13 02:04 UTC, Fombi-Favour commented on spec/models/post_spec.rb
> +      initial = User.find(1).post_counter
I ran the test code and its a pass
![Screenshot 2024-01-13 020348](https://github.com/Fombi-Favour/blog-app-rb/assets/77404317/ab7a2ec8-1492-4e05-b1c8-f0dc9fa6149b)

2024-01-13 03:24 UTC, shahadat3669 approved these changes
Hi @Fombi-Favour, 

Your project is complete!  There is nothing else to say other than it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights
✅ Worked on previous reviewer comments.
✅ All test cases passed.


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-13 03:25 UTC, merged