Blog app - controllers specs
Fombi-Favour/blog-app-rb pull request #5
Opened 2024-01-17 08:23 UTC by Fombi-Favour

In this activity, we:
- created a `request` folder in the `spec` directory
- added test for the `users` and `posts` controllers

2024-01-17 11:52 UTC, DammyShittu requested changes
Hi @Fombi-Favour,

## Highlights
✔️ Rspec test suite

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-17 11:52 UTC, DammyShittu commented on spec/requests/posts_request_spec.rb
> +  end
- [x] Kindly separate these two tests into different describe blocks as they test for different controller actions.

  ```
  describe 'GET /index' do
    # index page tests
  end

  describe 'GET /show' do
    # show page tests
  end
  ```

2024-01-17 11:52 UTC, DammyShittu commented on spec/requests/users_request_spec.rb
> +  end
- [x] Kindly separate these two tests into different describe blocks as they test for different controller actions.

  ```
  describe 'GET /index' do
    # index page tests
  end

  describe 'GET /show' do
    # show page tests
  end
  ```

2024-01-17 11:52 UTC, DammyShittu commented on spec/requests/posts_request_spec.rb
> +    end
- [ ] Kindly add test to assert the index template is rendered.

2024-01-17 11:52 UTC, DammyShittu commented on spec/requests/posts_request_spec.rb
> +      expect(response.body).to include('Individual post')
- [ ] Kindly add test to assert the show template is rendered.

2024-01-17 11:52 UTC, DammyShittu commented on spec/requests/users_request_spec.rb
> +    end
- [ ] Kindly add test to assert the index template is rendered.

2024-01-17 11:52 UTC, DammyShittu commented on spec/requests/users_request_spec.rb
> +    end
- [ ] Kindly add test to assert the show template is rendered.

2024-01-17 11:52 UTC, DammyShittu commented on spec/requests/posts_request_spec.rb
> +    it 'renders a successful response' do
- [ ] Your tests are failing. Kindly fix them.

  ![image](https://github.com/Fombi-Favour/blog-app-rb/assets/54848363/1324b147-6791-4d84-9518-577306fcdd4b)

2024-01-17 11:57 UTC, Fombi-Favour commented on spec/requests/posts_request_spec.rb
> +    end
Please I tried to add it into the test but it was not working. Can you please tell an alternative way of rendering the template.
I used this: `expect(response).to render_template('users/index')` but not working. Same as for the posts test

2024-01-18 00:44 UTC, rloterh commented on spec/requests/posts_request_spec.rb
> +  end
well resolved! ✔️

2024-01-18 00:45 UTC, rloterh commented on spec/requests/users_request_spec.rb
> +  end
well resolved! ✔️

2024-01-18 00:45 UTC, rloterh commented on spec/requests/posts_request_spec.rb
> +    end
well resolved! ✔️

2024-01-18 00:45 UTC, rloterh commented on spec/requests/posts_request_spec.rb
> +      expect(response.body).to include('Individual post')
well resolved! ✔️

2024-01-18 00:45 UTC, rloterh commented on spec/requests/posts_request_spec.rb
> +    it 'renders a successful response' do
well resolved! ✔️

2024-01-18 00:45 UTC, rloterh commented on spec/requests/users_request_spec.rb
> +    end
well resolved! ✔️

2024-01-18 00:46 UTC, rloterh commented on spec/requests/users_request_spec.rb
> +    end
well resolved! ✔️

2024-01-18 00:49 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Favour,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Good job on implementing recommended changes!

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
Let's make the ReadMe stand out even better by including instructions under the _Getting Started_ section, on how to run test cases for the app, for instance, using the command `rspec`.

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-18 00:50 UTC, merged